### ISSUE TITLE
Deploy Cabana's assets to an AWS account with OIDC authentication, no saved credentials

### ISSUE THREAD

**Issue by dnaphas-vri** [VerticalRelevance/cabana#7]
Use https://github.com/VerticalRelevance/aws-github-oidc to ensure that an OIDC Provider is present in the account.

**Comment by douglasnaphas** [comment]
When I add the Conditions to the Role that my Provider will assume, similar to [these](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy):

```json
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}
```

I can determine the org (`octo-org`) and the repo `octo-repo` from the environment variables available to GitHub Actions. They won't need to be manually updated in each repo. They will always be for the current org, and the current repo. The filter (`refs/heads/octo-branch`) can vary based on whether it's the main deployment action or a feature branch deployment. I may be able to determine the current branch and the default branch for the repo using Git commands and GitHub Actions variables.

**Comment by douglasnaphas** [comment]
Do I need to make sure that the role exists when they deploy the app stack?

Should the role stack be in a separate app in the same repo?

One role per repo (org and repo name), right? Not one per branch? It would be annoying to have to run a CLI command to deploy the role once once for every branch.

**Comment by douglasnaphas** [comment]
A role per branch is fine, actually.

**Comment by douglasnaphas** [comment]
Not sure what to do about [this](https://github.com/VerticalRelevance/cabana/actions/runs/5812436528/job/15757834232).

`"An unknown error occurred"`.

![Screenshot 2023-08-09 at 2 14 03 PM](https://github.com/VerticalRelevance/cabana/assets/5433410/f04dc496-f8fa-409a-bf6c-3377c5d75664)


![Screenshot 2023-08-09 at 2 11 39 PM](https://github.com/VerticalRelevance/cabana/assets/5433410/9753ed7f-a306-4924-9594-6409db02ed42)
![Screenshot 2023-08-09 at 2 11 52 PM](https://github.com/VerticalRelevance/cabana/assets/5433410/73a45569-fe01-4849-8eb3-375e5ecc1a42)
![Screenshot 2023-08-09 at 2 12 19 PM](https://github.com/VerticalRelevance/cabana/assets/5433410/013e96cd-7a9d-4a73-b888-29093b47d922)


```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "WebIdentityUser",
        "principalId": "arn:aws:iam::105379901447:oidc-provider/token.actions.githubusercontent.com:sts.amazonaws.com:repo:VerticalRelevance/cabana:ref:refs/heads/master",
        "userName": "repo:VerticalRelevance/cabana:ref:refs/heads/master",
        "identityProvider": "arn:aws:iam::105379901447:oidc-provider/token.actions.githubusercontent.com"
    },
    "eventTime": "2023-08-09T17:58:17Z",
    "eventSource": "sts.amazonaws.com",
    "eventName": "AssumeRoleWithWebIdentity",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "40.75.123.241",
    "userAgent": "aws-sdk-nodejs/2.1396.0 linux/v16.16.0 configure-aws-credentials-for-github-actions promise",
    "errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
    "requestParameters": {
        "roleArn": "arn:aws:iam::105379901447:role/sVcmas-bbd933-role-GitHubRoleECD51173-89CYB55967ID",
        "roleSessionName": "GitHubActions",
        "durationSeconds": 3600
    },
    "responseElements": null,
    "requestID": "5d1f77eb-b21e-4728-9eb2-76321690ddc4",
    "eventID": "cad771e1-5ea0-495b-85a8-8dd6da571b19",
    "readOnly": true,
    "resources": [
        {
            "accountId": "105379901447",
            "type": "AWS::IAM::Role",
            "ARN": "arn:aws:iam::105379901447:role/sVcmas-bbd933-role-GitHubRoleECD51173-89CYB55967ID"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "105379901447",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "sts.us-west-2.amazonaws.com"
    }
}
```

**Comment by douglasnaphas** [comment]
I fixed the above by changing my condition on the `aud` claim from `sts.amazon.com` to `sts.amazonaws.com`.

**Comment by douglasnaphas** [comment]
I think I need to do [this](https://docs.github.com/en/actions/learn-github-actions/variables#passing-values-between-steps-and-jobs-in-a-workflow). I need to figure out the role name in one step, then write it to a GITHUB_ENV file so I can use it in the configure-credentials step.

**Comment by douglasnaphas** [comment]
I could just have people deploy the role stack from the CLI, and save like `PROD_ROLE`, `TEST_ROLE`, `DEV_ROLE` (per-branch basis) in Secrets or variables.

**Comment by douglasnaphas** [comment]
Resources deployed, closing.
